# Run during the 'gulp build' command
# Overrides these options in _config.yml

# Hides your drafts and future posts
future: false
show_drafts: false
# Removes the upper limit for posts generated
limit_posts: 0
