name = "apis-guru-workers"
compatibility_date = "2025-07-01"
compatibility_flags = ["nodejs_compat"]

# Environment configuration for Pages Functions
pages_build_output_dir = "out"

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "apis-guru-data"
database_id = "660cdfd3-7c06-44ea-8e6d-f658f4fc39ca" # Replace with actual database ID from wrangler d1 create



# Environment variables
[vars]
SYNC_URL = "https://api.apis.guru/v2/list.json"
BATCH_SIZE = "100"
MAX_PAGE_SIZE = "100"
DEFAULT_PAGE_SIZE = "20"

# Preview configuration (renamed from development)
[env.preview]
[[env.preview.d1_databases]]
binding = "DB"
database_name = "apis-guru-data"
database_id = "your-dev-database-id"

# Production configuration
[env.production]
[[env.production.d1_databases]]
binding = "DB"
database_name = "apis-guru-data"
database_id = "660cdfd3-7c06-44ea-8e6d-f658f4fc39ca"
