openapi: 3.0.3
info:
  title: Quotes API
  version: "1.0"
  description: >
    An API for retrieving quotations.
    
    This OpenAPI definition defines the following endpoints:

    * `/quotes`: This endpoint returns all quotes.
    * `/quotes/author`: This endpoint returns quotes by the specified author.
    * `/quotes/source`: This endpoint returns quotes from the specified source.
    * `/quotes/random`: This endpoint returns a random number of quotes.

    The `Quote` schema defines the properties of a quote.
paths:
  /quotes:
    get:
      tags:
        - Quotes
      summary: Get all quotes.
      responses:
        200:
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Quote"
      description: Returns all quotes.

  /quotes/author:
    get:
      tags:
        - Quotes
      summary: Get quotes by author.
      parameters:
        - name: author
          in: path
          required: true
          type: string
      description: The author of the quotes to retrieve.
      responses:
        200:
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Quote"
      description: Returns quotes by the specified author.

  /quotes/source:
    get:
      tags:
        - Quotes
      summary: Get quotes by source.
      parameters:
        - name: source
          in: path
          required: true
          type: string
      description: The source of the quotes to retrieve.
      responses:
        200:
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Quote"
      description: Returns quotes from the specified source.

  /quotes/random:
    get:
      tags:
        - Quotes
      summary: Get random quotes.
      parameters:
        - name: limit
          in: query
          required: false
          type: string
          description: The number of quotes to return.
      responses:
        200:
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Quote"
      description: Returns a random number of quotes.
components:
  schemas:
    Quote:
      type: object
      properties:
        id:
          type: string
        author:
          type: string
        source:
          type: string
        quote:
          type: string
