name: deploy

# Author: @MikeRalphson
# Issue : n/a
# Desc  : This workflow runs a build and deploy to the gh-pages branch for an 11ty project

# run this on push to code-red-updates
on: 
  push:
    branches: [code-red-updates]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1 # checkout repo content
    - uses: actions/setup-node@v1 # setup Node.js
      with:
        node-version: '12.x'
    - name: Audit package-lock.json
      run: npx package-lock-audit ./package-lock.json
    - name: Install deps
      run: npm i
    - name: Run lint
      run: npm run lint
    - name: Run sass
      run: npm run sass
    - name: Run build
      run: npm run build
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@4.0.0
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: _site # The folder the action should deploy.
